# Generated by Django 4.0.3 on 2022-03-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='color',
        ),
    ]
