# Generated by Django 4.0.3 on 2022-03-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_photo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='grayScale',
        ),
    ]
